### PR TITLE
fix(web-app): convert /elemenets/icons/library to JS page

### LINKED ISSUE #1446: Convert MDX pages to JS pages
https://github.com/carbon-design-system/carbon-platform/issues/1446#tasklist-block-7f80b01d-5c99-4848-bc1d-924abaaea5df

### PR DESCRIPTION
**Pull request by francinelucca**
Closes #1446 
 
- Converts /elements/icons/library to a JS page
- Removes `IconLibrary` and `PictogramLibrary` exports as MDX components
- Fixes NullPointer on debounce time when clearing search input

#### Changelog

**Changed**

- services/web-app/components/svg-libraries/icon-library/icon-library.js: Fix NullPointer on debounce time when clearing search input
- services/web-app/components/svg-libraries/pictogram-library/pictogram-library.js: Fix NullPointer on debounce time when clearing search input
- services/web-app/pages/elements/icons/library.js: make a JS page

**Removed**

- services/web-app/components/mdx/components.js: remove `IconLibrary` , `PictogramLibrary` exports
- services/web-app/pages/mdx/pictograms.mdx: no longer needed

#### Testing / reviewing

http://localhost:3000/elements/icons/library compare to https://next.carbondesignsystem.com/elements/icons/library

### CODE REVIEW

File: services/web-app/pages/elements/icons/library.js [hunk 1]
```diff
@@ -0,0 +1,77 @@
...
+        <IconLibrary iconCategoryMetadata={iconCategoryMetadata} iconMetadata={iconMetadata} />
+      </ContentWrapper>
+    </>
+  )
+}
+
+export const getStaticProps = async () => {
+  // This is not using ISR because it gets is data from a local dep that ends up bundled with the
+  // web-app. ISR would just pull from the same local dep. A future implementation might pull this
+  // from someplace like unpkg or directly from github instead
```
Comment (andreancardona) [inline services/web-app/pages/elements/icons/library.js:65]:
```suggestion
  // from some place like unpkg or directly from github instead.
```

File: services/web-app/pages/elements/icons/library.js [hunk 2]
```diff
@@ -0,0 +1,77 @@
...
+      <ContentWrapper>
+        <IconLibrary iconCategoryMetadata={iconCategoryMetadata} iconMetadata={iconMetadata} />
+      </ContentWrapper>
+    </>
+  )
+}
+
+export const getStaticProps = async () => {
+  // This is not using ISR because it gets is data from a local dep that ends up bundled with the
+  // web-app. ISR would just pull from the same local dep. A future implementation might pull this
```
Comment (andreancardona) [inline services/web-app/pages/elements/icons/library.js:64]:
```suggestion
  // web-app. ISR would just pull from the same local dependency. A future implementation might pull this
```

Comment (andreancardona) [reply services/web-app/pages/elements/icons/library.js:64]: this is just me...being nit picky 😅  all looks good though!!

**Review by andreancardona — APPROVED** [review]

**Review by alisonjoseph — APPROVED** [review]
