### PR TITLE
Data Graph first pass and other assorted changes

### LINKED ISSUE #326: API package: trace method decorator enhancement
incorporate messaging into `Trace()` and make it more general purpose
packages/api/src/main/microservice/decorators/Trace.ts

### LINKED ISSUE #593: Environment Logging: test env logging prod env errors
### Browser

_No response_

### Description

the test logger is logging the production errors in addition to the prod logger 

from @jdharvey-ibm:
"I think this line 111 is the reason for the duplicate logging:
The name of the exchange should be environment-specific like the way that the queues are. It'd involve a cascading change in the messaging-client.ts too everywhere either an EventMessage or QueryMessage are used."
image

### Steps to reproduce

-

### LINKED ISSUE #624: Create/expose a graphql tagged template literal
Devs should be able to write graphql queries in a template literal that is compatible with IDE tooling to ensure well-formed queries.

```ts
gql`query {...}` // for example
```

This involves taking the gql tagged template literal that is exposed by NestJS and exporting it as part of the data-graph package.

### LINKED ISSUE #631: Create data-graph service package
create the service folder (package.json, tsconfig, etc.) for the data graph service.

### LINKED ISSUE #632: Move nestjs data-graph PoC code into the service package
Take a pass through the PoC code:

- [ ] Perform cleanup
- [ ] Ensure currency with how platform microservices are defined
- [ ] Create any appropriate scripts in the package.json file to run, test, and build the service.

### LINKED ISSUE #633: Create finalized organizational structure of data-graph code and resolvers
Make sure that enough thought goes into the code layout in the data graph service so that it can scale to dozens of resolvers without being confusing for maintainers or code explorers who want to see what resolvers are available.

### LINKED ISSUE #637: Docs: data-graph service documentation
- [ ] Document how the service works
- [ ] Document how the test infrastructure works
- [ ] Document the graph ql schema

### LINKED ISSUE #686: Hook up data graph to messaging
The data graph should work as both a web-accessible API and via messaging. This issues is the effort to get it hooked up to the messaging infrastructure. This involves:

- define a queue for the data-graph service
- define events and queries
- define interfaces for inputs and outputs
- create callable APIs in the api package
- figure out a way to sustainably register more than one nestjs app module on the same port via the PlatformMicroservice class.

### PR DESCRIPTION
**Pull request by jharvey10**
Closes #593
Closes #631
Closes #632 
Closes #633
Closes #326
Closes #686
Closes #637
Closes #624

### TODO:

- [x] update docs for:
  - [x] Trace
  - [x] api/messaging
  - [x] api/microservice
  - [x] data-graph service
  - [x] api/environment
- [x] add unit tests for data graph service
- [x] expose gql tagged template
- [x] hook up to messaging infrastructure
- [x] clean up todos in messaging `interfaces.ts`
- [x] Dockerfile

#### Changelog

**New**

- data-graph service!
- add some dummy models for now (libraries and users)
- add QueryResult class in preparation for messaging hookup
- `Trace` is now fully functional and fully documented (in the code)
- auto-log requests through microservices
- auto-catch certain types of exceptions in microservices
- add new `withEnvironment` function in environment.ts
- lots-o-unit tests

**Changed**

- improved some eslint rules
- logging now no longer requires a service name, but a service name envvar will now be enforced in Standard run mode (`CARBON_SERVICE_NAME`)
- better logging console output colors
- better way to disable remote logging
- fix bugs with messaging queue acks
- drastically improve the way in which `emit` and `query` are worked with
- drastically improve the developer experience for defining microservices bound to message types
- consistent kebab-case naming across files

**Removed**

- test coverage collection from index files and data-graph models
- remove a bunch of code from platform-microservice
- remove `Validate` decorator in favor of calling the validator inline in the handler methods instead.

### CODE REVIEW

File: services/data-graph/src/main/index.ts [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+ * This source code is licensed under the Apache-2.0 license found in the
+ * LICENSE file in the root directory of this source tree.
+ */
+import { QueryMessage, Queue } from '@carbon-platform/api/dist/main/messaging'
+import { PlatformMicroservice } from '@carbon-platform/api/microservice'
+
+// import { NestFactory } from '@nestjs/core'
+// import { GraphQLSchemaHost } from '@nestjs/graphql'
+// import { gql } from 'apollo-server-express'
+// import { execute, graphql } from 'graphql'
```
Comment (francinelucca) [inline services/data-graph/src/main/index.ts:13]:
```suggestion

```

File: services/data-graph/src/main/index.ts [hunk 2]
```diff
@@ -0,0 +1,66 @@
...
+  //   client
+  //     .query(queryType, {
+  //       queryName: 'user',
+  //       query: 'query{user(id: 2){name, email, id}}'
+  //     })
+  //     .then((res) => {
+  //       console.log('promised resolved', res)
+  //     })
+  // }, 1000)
+}
```
Comment (francinelucca) [inline services/data-graph/src/main/index.ts:64]: are we keeping these for a reason?
```suggestion
```

File: packages/api/src/main/data-graph/outputs/query-result.ts [hunk 3]
```diff
@@ -0,0 +1,15 @@
...
+ */
+import { Library } from '../models/library.model'
+import { User } from '../models/user.model'
+
+class QueryResult {
+  public libraries?: Array<Library>
+  public users?: Array<User>
+}
+
+export { QueryResult }
```
Comment (francinelucca) [inline packages/api/src/main/data-graph/outputs/query-result.ts:15]: where is this used? 🤔

**Review by francinelucca — CHANGES_REQUESTED** [review]

File: packages/api/src/main/data-graph/models/library.model.ts [hunk 4]
```diff
@@ -0,0 +1,60 @@
...
+  inherits?: string
+
+  @Field(() => String, { defaultValue: defaultValues.packageJsonPath })
+  packageJsonPath: string = defaultValues.packageJsonPath
+
+  @Field(() => String, { nullable: true })
+  externalDocsUrl?: string
+
+  @Field(() => [String], { defaultValue: defaultValues.demoLinks })
+  demoLinks: string[] = defaultValues.demoLinks
```
[the remark this answers is not in the document]
Comment (jdharvey-ibm) [reply packages/api/src/main/data-graph/models/library.model.ts:40]: Good catch! I'll update that.

File: packages/api/src/main/data-graph/models/library.model.ts [hunk 5]
```diff
@@ -0,0 +1,60 @@
...
+  @Field(() => Boolean, { defaultValue: defaultValues.noIndex })
+  noIndex: boolean = defaultValues.noIndex
+
+  /**
+   * A constructor for the required fields of a library.
+   *
+   * @param library An object containing the required fields of the library.
+   * @param library.id The identifier of the library.
+   * @param library.name The name of the library.
+   * @param library.description The description of the library.
```
[the remark this answers is not in the document]
Comment (jdharvey-ibm) [reply packages/api/src/main/data-graph/models/library.model.ts:51]: So this is where things get a little interesting! Yes, the description is not required in the schema, but all library *objects* need to have a description attached to them. If one is not specified, it will default to the package.json value, but since there's a default value, it will always be present when returned by the data graph.

File: services/data-graph/src/main/index.ts (hunk 2 above)
Comment (jdharvey-ibm) [reply services/data-graph/src/main/index.ts:64]: These are kind of my notes for the messaging hook-up which I haven't done yet, haha. Eventually on this PR I will remove them though.

File: packages/api/src/main/data-graph/outputs/query-result.ts (hunk 3 above)
Comment (jdharvey-ibm) [reply packages/api/src/main/data-graph/outputs/query-result.ts:15]: It'll be used by the messaging infrastructure which is coming soon :)

File: packages/api/src/main/data-graph/models/library.model.ts (hunk 5 above)
[the remark this answers is not in the document]
Comment (francinelucca) [reply packages/api/src/main/data-graph/models/library.model.ts:51]: ahh ok! 👍

File: docs/services-data-graph.md [hunk 6]
```diff
@@ -0,0 +1,86 @@
...
+  body: JSON.stringify({
+    query: gql`
+      ...
+    `,
+    variables: {
+      ...
+    }
+  }),
+  headers: {'Content-Type': 'application/json'}
+})
```
Comment (francinelucca) [inline docs/services-data-graph.md:54]: is this already implemented? or that's how it's going to work?

File: services/data-graph/src/main/validate-data-graph-message.ts [hunk 7]
```diff
@@ -0,0 +1,23 @@
...
+ * Copyright IBM Corp. 2022, 2022
+ *
+ * This source code is licensed under the Apache-2.0 license found in the
+ * LICENSE file in the root directory of this source tree.
+ */
+import { DataGraphMessage } from '@carbon-platform/api/data-graph'
+import { UnvalidatedMessage } from '@carbon-platform/api/messaging'
+import { InvalidInputException } from '@carbon-platform/api/microservice'
+
+function validateDataGraphMessage(data: UnvalidatedMessage): DataGraphMessage {
```
Comment (francinelucca) [inline services/data-graph/src/main/validate-data-graph-message.ts:11]: curious what would happen if the query was a valid string and the variables was a valid object but it didn't contain a key that was needed? 🤔

File: services/data-graph/src/test/data-graph-module.e2e-test.ts [hunk 8]
```diff
@@ -0,0 +1,72 @@
...
+      })
+
+    expect(response.statusCode).toBe(200)
+    expect(response.body.data).toHaveProperty('libraries')
+    expect(response.body.data.libraries).toContainEqual(expect.objectContaining({ id: 'lib1' }))
+  })
+
+  it('returns single user', async () => {
+    const response = await request(app.getHttpServer())
+      .post('/graphql')
```
Comment (francinelucca) [inline services/data-graph/src/test/data-graph-module.e2e-test.ts:48]: where is this endpoint defined? does it just exist out of the box because we're running a nestjs graphql module?

**Review by francinelucca — COMMENTED** [review]
Looking good! TIL: jest.spyOn 🎉 .
I have NO idea **how** that gql template literal works but I get what it does (I think?) 😆

File: docs/services-data-graph.md (hunk 6 above)
Comment (jdharvey-ibm) [reply docs/services-data-graph.md:54]: Yeah! This should work as-is on this PR. I imagine we won't use this one much though and we'll mostly be using the messaging one and requesting the data server-side.

File: services/data-graph/src/test/data-graph-module.e2e-test.ts (hunk 8 above)
Comment (jdharvey-ibm) [reply services/data-graph/src/test/data-graph-module.e2e-test.ts:48]: Yep! We get the endpoint for free by sprinkling in the GraphQLModule when creating the nest app.

File: services/data-graph/src/main/validate-data-graph-message.ts (hunk 7 above)
Comment (jdharvey-ibm) [reply services/data-graph/src/main/validate-data-graph-message.ts:11]: You can kinda think of this as the first level of message validation (one of two). This one makes sure that the incoming message from the broker has the expected properties based on its interface.

The second one is the actual invocation of `graphql(...)` over in https://github.com/carbon-design-system/carbon-platform/pull/720/files#diff-ca57878b44a9309813e113add66fff05e4f11acd3f58cbec1bda4ea7a87d3f1dR49

That's the one that takes the actual graphql schema as input and validates the incoming query. If it's malformed, that will generate errors which will end up in the `{errors: ...}` section of the query response.
