### PR TITLE
fix(web-app): add spacer columns to catalog multiselect filter

### LINKED ISSUE #1153: Catalog filter dropdown line
The current filter has the second line only extending half way down the filter: 
Screen Shot 2022-08-18 at 9 26 50 AM

it should extend the length of the filter with 32px `$spacing-07`:
image

### PR DESCRIPTION
**Pull request by francinelucca**
Closes #1153 

Add necessary spacer columns (if any) to multiselect filter display so that the border shows up across the whole line.

#### Changelog

**Changed**

- services/web-app/components/catalog-multislect-filter/catalog-multiselect-filter.js: add and use `addSpacerColumns` function

#### Testing / reviewing

Test multiselect filter across different breakpoints, should behave the same except visually all line borders should go all the way down

http://localhost:3000/assets/patterns
http://localhost:3000/assets/components
http://localhost:3000/assets/functions
http://localhost:3000/assets/templates

### CODE REVIEW

File: services/web-app/components/catalog-multislect-filter/catalog-multiselect-filter.js [hunk 1]
```diff
@@ -62,6 +62,19 @@ const CatalogMultiselectFilter = ({
     return sum + filter[item].length
   }, 0)
 
+  const addSpacerColumns = () => {
+    if (Object.keys(availableFilters).length % columns > 0) {
+      const spacerCols = []
```
Comment (andreancardona) [inline services/web-app/components/catalog-multislect-filter/catalog-multiselect-filter.js:67]: just curious if you think it's worth extracting `Object.keys(availableFilters).length` into a variable ?

**Review by andreancardona — APPROVED** [review]
looks good! just a comment / question

**Review by alisonjoseph — APPROVED** [review]
LGTM
